### ISSUE TITLE
Support configurations

### ISSUE THREAD

**Issue by harryzcy** [harryzcy/snuuze#24]
- [x] Configuration from yaml file #26
- [x] Set authentication methods, i.e. PAT or GitHub app and Gitea App #39 
- [x] Support configuration from environment variables #26
